### ISSUE TITLE
No exons in transcript model.

### ISSUE THREAD

**Issue by jfjlaros** [mutalyzer/mutalyzer#20]
When a [transcript](http://v3.mutalyzer.nl/namechecker/NM_002001.2:c.10del) is used in the name checker, error `ESELECTORMODELNOEXONS` may be raised. The name checker can and should continue in this case, by assuming that the whole transcript is one big exon.

**Comment by mihailefter** [comment]
Fixed. However, there is no info/warning message provided. I leave it open until we implement that functionality.
