### ISSUE TITLE
"Could not get mapping information for gene" error when running sliceChromosomeByGene (webservices and website) 

### ISSUE THREAD

**Issue by ifokkema** [mutalyzer/mutalyzer#351]
Hi there,

The webservices and website of Mutalyzer currently can't generate UDs by gene symbol:

```
https://mutalyzer.nl/json/sliceChromosomeByGene?geneSymbol=IVD&organism=Man&upStream=5000&downStream=2000
{"faultcode": "ERETR", "faultstring": "Could not get mapping information for gene IVD."}
```

The website also can't:
```
Reference File not loaded!
The following errors occured:
    The request could not be completed
    Fatal (Retriever): Could not get mapping information for gene IVD.
```

Whereas the position converter seems to run just fine for IVD.
This does not seem to be limited to just one gene, it seems to be failing on all genes at the moment.

Is this a problem that has to do with the NCBI?

**Comment by martijnvermaat** [comment]
I cannot reproduce this at the moment and I see some errors related to NCBI Entrez in the log file for last night, so I would think it was a temporary problem at the NCBI.

Feel free to reopen if you still have problems.

**Comment by ifokkema** [comment]
Could the error message be improved? "Could not get mapping information for gene IVD." sounds a bit general, especially since Mutalyzer provides mapping information as well. Perhaps add in the error message that this is NCBI related and may be a temporary error? Something like "please try again in an hour or so" might prevent users from emailing you / submitting bug reports, which may save you some time later ;)

**Comment by martijnvermaat** [comment]
Good point, I'll do that.
