### ISSUE TITLE
Position Converter error?: 1 off

### ISSUE THREAD

**Issue by jtdendunnen** [mutalyzer/mutalyzer#360]
According to the Name Checker NM_003319.3:c.29752G>A (TTN) is correct. Using the Position Converter NM_003319.3:c.29752G>A should equal NM_001267550.1:c.56948G>A. This is not correct, it should be 56947G>A. The same mistake, 1 nucleotide difference, is made for all nucleotides downstream of NM_003319.3:c.29752G>A (NM_003319.3:c.26945C>T is still OK).

**Comment by martijnvermaat** [comment]
Thanks for the report.

Note that `NM_003319.3` has been replaced by `NM_003319.4` on March 13, 2010. The latter is mapped in the way you describe as correct.

There are three sequence differences between the two:
1. `211_212insG`
2. `29057del`
3. `29083dup`
(So version 4 is one nucleotide longer, 82028 versus 82029.)

The NCBI Map Viewer (which we use as a source for the position converter) places 188 exons (out of 191) identically on hg19 for both transcript versions. The remaining three are mapped as follows:

start (3) | stop (3) | start (4) | stop (4)
--------- | -------- | --------- | --------
179464281 | 179464575 | 179464281 | 179464577
179465580 | 179465898 | 179465581 | 179465898
179671940 | 179672150 | 179671939 | 179672150

(CDS start and stop are mapped to 179391739 and 179669369 for both versions.)

The UCSC Genome Browser only contains the latest version (4), so I can't compare to their mapping of version 3.

Please let me know if you still think something's wrong here.

**Comment by martijnvermaat** [comment]
Closing as a don't think the error is in Mutalyzer.
