### ISSUE TITLE
wrong position returned by position converter via https/json

### ISSUE THREAD

**Issue by ugeigenmuller** [mutalyzer/mutalyzer#362]
Variant:
NM_000388.3:c.1732+16T>C

manual use of website
NC_000003.11:g.122001099T>C

https://mutalyzer.nl/json/numberConversion?build=hg19&variant=NM_000388.3:c.1732+16T>C
["NC_000003.11:g.122174017T>C"]

This happened for about 10% of about 4000 variants tested.

**Comment by martijnvermaat** [comment]
Hi @ugeigenmuller, thanks for the report!

I think I know what is going on here. Using the JSON webservice, arguments are passed as HTTP query string parameters and therefore [need to be encoded](https://en.wikipedia.org/wiki/Query_string#URL_encoding) as such. Amongst the reserved characters in the query string is `+`, and this is probably the reason some of your variant descriptions are being misinterpreted.

For example, the request you show should be:

https://mutalyzer.nl/json/numberConversion?build=hg19&variant=NM_000388.3%3Ac.1732%2B16T%3EC

Depending on the programming language you are using, there's probably a library which you can use for this. [Here's an interface](http://meyerweb.com/eric/tools/dencoder/) to do it directly from your browser.

We'll update the text on the website to mention this, I think it's a very unfortunate pitfall.

**Comment by ugeigenmuller** [comment]
Thanks so much for your quick help!
