### ISSUE TITLE
containerized mutalyzer

### ISSUE THREAD

**Issue by p7k** [mutalyzer/mutalyzer#367]
Hi @martijnvermaat,

Thanks again for you work on Mutalyzer.
Just wanted to bring your attention to this:

https://hub.docker.com/r/eidetiq/docker-mutalyzer/
https://github.com/p7k/docker-mutalyzer

Let me know if you'd rather "merge" it more closely into the Mutalyzer ecosystem.

**Comment by martijnvermaat** [comment]
Hi @p7k ,

That looks great! :+1:  What are you using it for?

Did you encounter anything in Mutalyzer that could be improved to make this easier?

I wouldn't have a problem brining it under the Mutalyzer GitHub organisation if you think that makes sense (we'd just add you as a member). Alternatively, I'm also happy to link to it from our documentation.

**Comment by p7k** [comment]
Thanks!  It still has quite a bit of room for improvement, but it gets the job done (for me, it's running large batches of dbSNP rsID and HGVS conversions to chromosomal positions).

Running against internal deployments of Mutalyzer helps a bit with network predictability and privacy.  Mutalyzer handles rsID lookups via Entrez - so privacy is a tough to guarantee, but it's step in that general direction :)

I think, it could be useful to others - let's expose it through the Mutalyzer org.

**Comment by martijnvermaat** [comment]
Good to hear. Let's do it that way. I just created a team for this in the organization and invited you as a member. If you accept it you should be able to transfer the project.

**Comment by martijnvermaat** [comment]
Closing this as the project is now in the Mutalyzer org. Thanks!
