### ISSUE TITLE
No output given for position converter for NM_003002.3:c.273G[3]

### ISSUE THREAD

**Issue by ifokkema** [mutalyzer/mutalyzer#375]
Hi there,

I was testing the current support for repeat sequences (related to #300), and noticed the position converter at a certain point stopped giving me a warning, but also gave no result.

```
NM_003002.3:c.273G>T
Result: proper mapping output.
```
```
NM_003002.3:c.273[3]
Result: Error: Could not parse the given variant
```
```
NM_003002.3:c.273[3]G    (VEP style repeat sequence nomenclature)
Result: Error: Could not parse the given variant
```
```
NM_003002.3:c.273G[3]
Result: Nothing. No error, but also no output.
```

**Comment by martijnvermaat** [comment]
Bit of a duct tape construction, but this specific case should now be handled by #376 (deployed on the test server).
