### ISSUE TITLE
Mutalyzer 2.0.19 has broken webservice

### ISSUE THREAD

**Issue by ifokkema** [mutalyzer/mutalyzer#393]
Hi,

The release today broke the functionality in all LOVDs worldwide, to create genes. The reason is that this webservice is suddenly returning Internal Errors:
```
https://mutalyzer.nl/json/sliceChromosome?chromAccNo=NC_000001.10&start=156047369&end=156111880&orientation=1
```
I have said before that our tests should be using test.mutalyzer.nl, and it seems again that would have saved us both a lot of trouble. I will create an issue for us, that we should do that.

Cheers,

Ivo

**Comment by martijnvermaat** [comment]
Sorry for this, I should've tested this better. Will try to release a fix before Monday.

**Comment by martijnvermaat** [comment]
Only slices that have been created before are affected by the way. I suspect this includes the majority of the calls done by LOVD since slices for most genes have been created at least once for the LOVD shared database.

**Comment by martijnvermaat** [comment]
@ifokkema I deployed a fix, all should be good now. Let me know if you notice anything broken.

**Comment by ifokkema** [comment]
Perfect, thanks! I will restart our tests :)
