### ISSUE TITLE
Provide grammar.py as standalone package on PyPI

### ISSUE THREAD

**Issue by cthoyt** [mutalyzer/mutalyzer#413]
We're working on a python parser for biological expression language (@pybel) that's also using PyParsing. The biological expression language actually defers to the HGVS variants and we've had to implement our own parser for HGVS. We just realized you've published this *awesome* implementation of HGVS already, and would love to use your work in the file [grammar.py](https://github.com/mutalyzer/mutalyzer/blob/master/mutalyzer/grammar.py) in place of the common variants we've encoded in PyParsing ourselves, [here](https://github.com/pybel/pybel/blob/develop/src/pybel/parser/parse_abundance_modifier.py).

Would you consider publishing the grammar parsing/testing as a stand-alone project in GitHub, and as a package on PyPI, so we (and hopefully others!) could easily use your work with `pip install mutalyzer`?

Otherwise I'm not sure how to best build on your work. If you have some suggestions, I'd love to hear them! Keep up the great work :)

**Comment by mihailefter** [comment]
The grammar is now available [here](https://pypi.org/project/mutalyzer-hgvs-parser/).
