### ISSUE TITLE
RNA descriptions.

### ISSUE THREAD

**Issue by jfjlaros** [mutalyzer/mutalyzer#42]
The following description (generated by Mutalyzer) is not accepted: `NG_012337.1(NM_003002.2):r.([274g>u;278u>g])`

**Comment by jfjlaros** [comment]
This issue has [not been resolved](https://mutalyzer.nl/normalizer/NG_012337.1(NM_003002.2):r.(%5B274g%3Eu;278u%3Eg%5D)).

**Comment by mihailefter** [comment]
What was the input that generated this RNA description?

**Comment by jfjlaros** [comment]
Does it matter? The description should be accepted as far as I can see.

**Comment by mihailefter** [comment]
That's my impression as well.

**Comment by jfjlaros** [comment]
False alarm then, my bad.
