### ISSUE TITLE
Missing fields in description extractor output.

### ISSUE THREAD

**Issue by jfjlaros** [mutalyzer/mutalyzer#42]
When the description extractor is called with the following arguments:

    Raw sequence: ATGATGATCAGATACAGTGTGATACAGGTAGTTAGACAA
    RefSeq accession number: NM_004006.2

The output shows an inversion where the deleted field is filled, but the inserted field is empty.

**Comment by martijnvermaat** [comment]
I think this is a bug in the description-extractor package, please re-open if that's incorrect.
