### ISSUE TITLE
How do I get 2.0.23 prod rather than 2.0.24DEV via ansible

### ISSUE THREAD

**Issue by christopherwelsh** [mutalyzer/mutalyzer#421]
Hi,

Trying to setup a custom prod version of Mutalyzer (or at least on that has version parity with your hosted version.

Unfortunately I have two questions:

1. I understand there is a "host_vars/mutalyzer" file that one can setup custom params. I see one in the "test" directory but where should the proper one go?
2. How and where do I set ansible to pull 2.0.23. Every time I try it builds 2.0.24 (nicely of course and it works, but I need version parity with what your primary site uses). 

Thanks
Chrisco

**Comment by mkroon1** [comment]
Mutalyzer's ansible role uses the `mutalyzer_git_branch` variable to determine which git branch to use for deployment (see a [description here](https://github.com/mutalyzer/ansible-role-mutalyzer#variables)). The default for this variable is `master`, which is what you are seeing. We use the branch `release` for our production server.

You can overwrite this variable in the `host_vars` directory like you said, or by setting it directly in the playbook or on the command line when running the playbook.

Cheers,
-- M

**Comment by christopherwelsh** [comment]
Thx. That did it. :-)
