### ISSUE TITLE
prefix changed (m. > g.)

### ISSUE THREAD

**Issue by jtdendunnen** [mutalyzer/mutalyzer#425]
HGVS has recently retracted the recommendation to indicate the use of a mitochondrial reference sequence using a "m." prefix. A mitochondrial sequence is, like that of a chloroplast, plasmid, viral genome sequence, etc. a genomic reference sequence and should be indicated by a "g". prefix. Please update Mutalyzer to correct descriptions using an "m." prefix.

**Comment by jfjlaros** [comment]
Is it correct that this decision has been reverted?
