### ISSUE TITLE
HTTP/RPC+JSON web service fails for intronic variants

### ISSUE THREAD

**Issue by jpuntomarcos** [mutalyzer/mutalyzer#435]
Hi,

I have noticed HTTP/RPC+JSON web service fails for intronic variants. For example, NM_000038.5:c.645+32C>A variant fails:
https://mutalyzer.nl/json/checkSyntax?variant=NM_000038.5:c.645+32C%3EA

whereby the same variant doesn't fail when using normal url:
https://mutalyzer.nl/syntax-checker?description=NM_000038.5%3Ac.645%2B32C%3EA

**Comment by jfjlaros** [comment]
This seems to be a URL encoding issue. The given example seems to work when we encode the '+':

https://mutalyzer.nl/json/checkSyntax?variant=NM_000038.5%3Ac.645%2B32C%3EA
