### ISSUE TITLE
position-converter TO name-checker ERROR

### ISSUE THREAD

**Issue by chdem** [mutalyzer/mutalyzer#469]
Hello,

I'm using position-converter to obtain a "c." notation for my specific transcript (`chr7:g.55228053A>T` to obtain`NM_005228.3:c.1498+22A>T`) :
https://mutalyzer.nl/position-converter?assembly_name_or_alias=GRCh37&description=chr7%3Ag.55228053A%3ET

But entering this notation (`NM_005228.3:c.1498+22A>T`) in name-checker throw an error (`Intronic position given for a non-genomic reference sequence.`) :
https://mutalyzer.nl/name-checker?description=NM_005228.3%3Ac.1498%2B22A%3ET

Did I miss something ?

Thank you.

**Comment by jfjlaros** [comment]
This is indeed confusing.

A transcript reference sequence does not contain any intronic sequences, this is why when we ask Mutalyzer to do a full check of this variant description, it raises this error.

The only way to check variants in an intron is to use a genomic reference sequence, for example:

    `NC_000007.13(NM_005228.3):c.1498+22A>T`
