### ISSUE TITLE
The wiki page is not available

### ISSUE THREAD

**Issue by HEKntg** [mutalyzer/mutalyzer#477]

**Comment by mihailefter** [comment]
Thanks for the notification. Could you please be more specific, i.e., what page was not available and when?

**Comment by HEKntg** [comment]
I found documents at https://mutalyzer.readthedocs.io/en/latest/ finally...
Thanks for replying.
I have another question:
Can I use _name-checker_ tool via the **Web Services** ? 
Just like:
https://mutalyzer.nl/json/name-checker?description=XXXXX
seems not working...

**Comment by jfjlaros** [comment]
You might want to check out the [API documentation](https://mutalyzer.nl/soap-api), the *runMutalyzer* or *runMutalyzerLight* is probably what you are looking for.

For example:

https://mutalyzer.nl/json/runMutalyzerLight?variant=NC_000011.9:g.111959695G>T

I hope this helps.

**Comment by jfjlaros** [comment]
By the way, the documentation you found is for installing a Mutalyzer server locally. User documentation can be found [here](https://github.com/mutalyzer/mutalyzer/wiki/Documentation) (via the menu **help**-**documentation** on the main site).

**Comment by HEKntg** [comment]
Thanks a lot!
