### ISSUE TITLE
Issue about SNP Converter

### ISSUE THREAD

**Issue by ionicbond2005** [mutalyzer/mutalyzer#482]
Hi,

I am trying to use batch SNP converter. However, when I try to give a list of rsID, the output was just Non existing "my rsID" in the DB or no root element.

I lookup some of my rsID on dbSNP and they are valid

Would you mind fixing this issue?

Thank you
[batch-job-a8f4acc7-b89d-4027-8968-ffceafcb7435.txt](https://github.com/mutalyzer/mutalyzer/files/3494594/batch-job-a8f4acc7-b89d-4027-8968-ffceafcb7435.txt)

Attached is the output

**Comment by jfjlaros** [comment]
Thank you for reporting this.

@mihailefter Apparently the NCBI response changed. The HGVS descriptions are now located in the `DOCSUM` tag.

**Comment by mihailefter** [comment]
@ionicbond2005 This issue is now fixed.

**Comment by ionicbond2005** [comment]
one question:

If the variant does not has an rsID, can mutalyzer use other information
such as chromosome + positon + reference allele + alternate alllele and
convert into HGVS nomenclature?

Thank you

**Comment by mihailefter** [comment]
@ionicbond2005 it looks like you have all the ingredients that constitute an HGVS description, so just put them together as a substitution variant ('`>`), include also the coordinate system (`.g`), and that's it. If you miss the `accession.version` of a chromosome, then you can make use of the [Position Converter](https://mutalyzer.nl/position-converter?assembly_name_or_alias=GRCh37&description=chr11%3Ag.111959693G%3ET) to retrieve it. Pass it next through the [Name Checker](https://mutalyzer.nl/name-checker?description=NC_000011.9%3Ag.111959693G%3ET) to see its correctness.

If you are actually interested in VCF to HGVS, then you can make use of [Mutalyzer Client](https://github.com/mutalyzer/client).
