### ISSUE TITLE
Mitochondrial reference not recognised.

### ISSUE THREAD

**Issue by jfjlaros** [mutalyzer/mutalyzer#49]
The following [description](https://v3.mutalyzer.nl/namechecker/NC_012920.1:m.3243A%3EG) gives an error, while none is expexted.

**Comment by mihailefter** [comment]
Maybe the correct approach would be to make `m.` as the **only** accepted coordinate system for `NC_012920.1`.

**Comment by jfjlaros** [comment]
I think `g.` should be allowed as input, but should not be returned.
