### ISSUE TITLE
About the reference of 13:46108853

### ISSUE THREAD

**Issue by SamGLZ** [mutalyzer/mutalyzer#500]
Hi Mutalyzer,

Thank you for the wonderful tool!  I have used it for years and it helped me a lot!

However, When I used Name-checker to search NM_031431.3:c.2474_2475invTG, I found that the reference nucleotides of position 13:46108853-46108854 are "CA" instead of "TG". I have checked the reference nucleotides in these positions on UCSC and NCBI, and results are both "TG". I have also checked gnomAD and found that the frequencies of these two variants were very high. 

I may have some mistakes in checking the reference,  but it does confuse me. It would be nice if someone can show me the reason for it. Thank you!

Sam

**Comment by mihailefter** [comment]
Hi Sam,

Thanks for using Mutalyzer.

It looks to me that the sequence in `NM_031431.3` is different than the one in `NC_000013.10`.
You can see that in Mutalyzer [NM](https://mutalyzer.nl/name-checker?description=NM_031431.3%3Ac.2474_2475invTG) vs [NC](https://mutalyzer.nl/name-checker?description=NC_000013.10(NM_031431.3)%3Ac.2474_2475invTG) as well as when using the NCBI viewer:

![image](https://user-images.githubusercontent.com/21262869/70519572-739edc00-1b3c-11ea-868d-78d27122e41d.png)

![image](https://user-images.githubusercontent.com/21262869/70519675-99c47c00-1b3c-11ea-9e9f-79c6ae82cb47.png)


Best regards,
Mihai
