### ISSUE TITLE
Inconsistent results between mutalyzer and ref genome fasta

### ISSUE THREAD

**Issue by xiucz** [mutalyzer/mutalyzer#501]
Hi, 
In the hg19 system, the base from positon  chr20:31022959 in UCSC or NCBI fasta is **T**， however, mutalyzer gives is **C** [](https://mutalyzer.nl/name-checker?description=NM_015338.5%3Ac.2443_2444insCA).

I am a little puzzled which one is the right answer?

Xiucz.
Thank you.

**Comment by jfjlaros** [comment]
The [name checker](https://mutalyzer.nl/name-checker?description=NC_000020.10%3A31022959del) gives the same result. Where does it say that there is a **C** at that position?

**Comment by jfjlaros** [comment]
Can not reproduce.
