### ISSUE TITLE
Silent mutations

### ISSUE THREAD

**Issue by lossinc** [mutalyzer/mutalyzer#505]
HGVS stipulates that synonymous/silent single-base exchanges should specify the non-affected amino acid (e.g., “p.Cys188=”, see [here](https://varnomen.hgvs.org/recommendations/protein/variant/substitution/)). Frankly, I wasn’t aware of this rule; I have been using p.= instead (leaving out the prediction parentheses here), but p.= is reserved to imply that there are no changes *anywhere* in the protein. Mutalyzer seems to make the same mistake, based on a recent check for NM_001290469.1:c.2406G>A, which ought to result in p.(Leu802=), no?

[https://mutalyzer.nl/name-checker?description=NM_001290469.1%3Ac.2406G%3EA](https://mutalyzer.nl/name-checker?description=NM_001290469.1%3Ac.2406G%3EA)

I might be wrong here, but I think p.(Leu802=) ought to be used.

Note: In this particular Mutalyzer example, I think the reference protein sequence as well as that of the unchanged protein sequence ought to be shown, both with Leu802 highlighted in red. Just a suggestion for user convenience.

**Comment by jfjlaros** [comment]
At the time that Mutalyzer was written, the goal of the HGVS nomenclature was to describe variants, over time this has shifted towards describing non-variants as well. This conflicts with the primary goal of the HGVS nomenclature, namely the disambiguation of variant descriptions.

Our position is that it should be possible to get a protein description from the original protein sequence and the observed protein sequence, independent from the underlying nucleotide changes. This is the only way to get the same description for variants that have the same effect, which is, in our opinion, a useful and desirable property of a variant description language.

In the Mutalyzer project, we have chosen to make variant disambiguation the priority, which means that the HGVS rules that conflict with this, can not be implemented.

Unfortunately, we have not been able to convince the HGVS nomenclature committee that this is a problem.
