### ISSUE TITLE
submitBatchJob error

### ISSUE THREAD

**Issue by peich69** [mutalyzer/mutalyzer#509]
Hi there,
I have write a simple perl script to:
-Check syntaxis of al my variants
-Get g. and p. nomenclature.
First part is done, using
'https://mutalyzer.nl/json/checkSyntax?&variant=NM_000XXX.X:c.000A>T'
the script makes a bucle over all variants and the ones that returns true, are saved into a file 'test.txt' with the format

NM_000XXX.X:c.000A>T
NM_000XXX.X:c.000A>T
NM_000XXX.X:c.000A>T

This part goes right. Now for testing, I'm using the file batchtestnew.txt for the second part.
I'm trying to do the second part with
'https://mutalyzer.nl/json/submitBatchJob?data='.encode_base64(batchtestnew.txt).'&process=NameChecker'
I get the response "343067f0-f71b-4e0c-94cb-8e22e10711a5" and then I use
'https://mutalyzer.nl/batch-job-result/batch-job-343067f0-f71b-4e0c-94cb-8e22e10711a5.txt'
The message I get is
Input	Errors and warnings	AccNo	Genesymbol	Variant	Reference Sequence Start Descr.	Coding DNA Descr.	Protein Descr.	GeneSymbol Coding DNA Descr.	GeneSymbol Protein Descr.	Genomic Reference	Coding Reference	Protein Reference	Affected Transcripts	Affected Proteins	Restriction Sites Created	Restriction Sites Deleted
C:\batchtestnew.txt	(grammar): Expected W:(0123...) (at char 1), (line:1, col:2)	
I don't understand what I'm doing wrong. I'm using a tutorial file so I assume that the file structure is not the problem.
Any suggestion?
Thanks

**Comment by jfjlaros** [comment]
Dear NN,

Thank you for using Mutalyzer.

It looks to me that you post the literal string `batchtestnew.txt` instead of
the contents of this file.

I hope this helps.


With kind regards,
Jeroen.

On Tue, Jul 07, 2020 at 02:04:12AM -0700, peich69 wrote:
> Hi there,
> I have write a simple perl script to:
> -Check syntaxis of al my variants
> -Get g. and p. nomenclature.
> First part is done, using
> 'https://mutalyzer.nl/json/checkSyntax?&variant=NM_000XXX.X:c.000A>T'
> the script makes a bucle over all variants and the ones that returns true, are saved into a file 'test.txt' with the format
> 
> NM_000XXX.X:c.000A>T
> NM_000XXX.X:c.000A>T
> NM_000XXX.X:c.000A>T
> 
> This part goes right. Now for testing, I'm using the file batchtestnew.txt for the second part.
> I'm trying to do the second part with
> 'https://mutalyzer.nl/json/submitBatchJob?data='.encode_base64(batchtestnew.txt).'&process=NameChecker'
> I get the response "343067f0-f71b-4e0c-94cb-8e22e10711a5" and then I use
> 'https://mutalyzer.nl/batch-job-result/batch-job-343067f0-f71b-4e0c-94cb-8e22e10711a5.txt'
> The message I get is
> Input	Errors and warnings	AccNo	Genesymbol	Variant	Reference Sequence Start Descr.	Coding DNA Descr.	Protein Descr.	GeneSymbol Coding DNA Descr.	GeneSymbol Protein Descr.	Genomic Reference	Coding Reference	Protein Reference	Affected Transcripts	Affected Proteins	Restriction Sites Created	Restriction Sites Deleted
> C:\batchtestnew.txt	(grammar): Expected W:(0123...) (at char 1), (line:1, col:2)	
> I don't understand what I'm doing wrong. I'm using a tutorial file so I assume that the file structure is not the problem.
> Any suggestion?
> Thanks
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mutalyzer/mutalyzer/issues/509

-- 
Jeroen F.J. Laros - J.F.J.Laros@lumc.nl

**Comment by peich69** [comment]
Dear Jeroen,
You are right.
I add a function to encode the file content, not the name file:

`
sub encode
{
    my $in_txt = $_[0];
    my $out_text = 'in_encoded';
    
    
    open INFILE,  '<', $in_txt;
    open OUTFILE, '>', $out_text;
    binmode OUTFILE;
    my $buf;
    while ( $buf = <INFILE> )
    {
        print OUTFILE encode_base64($buf);
    }

    close OUTFILE;
    close INFILE;
    return($out_text);
}
`


so, now the line is 
https://mutalyzer.nl/json/submitBatchJob?data=in_encoded&process=NameChecker
But gives the following error:
Error GETing https://mutalyzer.nl/json/submitBatchJob?data=in_encoded&process=NameChecker: Internal Server Error
I'm totally down.
Peich

**Comment by jfjlaros** [comment]
For this call, you need to use the POST method instead of GET.

Perhaps it is easier to use a webservices client [1].


References:
[1] https://metacpan.org/pod/release/MAKAMAKA/JSON-RPC-0.96/lib/JSON/RPC/Client.pm
