### ISSUE TITLE
IGV hg38 TTN gene no NM transcript id, only XM id

### ISSUE THREAD

**Issue by GiantVin** [mutalyzer/mutalyzer#511]
![hg19-TTN-IGV](https://user-images.githubusercontent.com/50960680/98150513-66958480-1e94-11eb-9404-68a079b83d87.png)
![TTN transcript ID issue-hg38-IGV](https://user-images.githubusercontent.com/50960680/98150514-672e1b00-1e94-11eb-8cbd-537d39d6996a.png)

Hi IGV team, 
We are using IGV hg38 for viewing NGS data, and found that for all exons of TTN gene it pops out only XM transcripts as shown in the screenshot (above 2). We used to use the NM to report like in hg19 screenshot (above 1). Could you fix it ASAP. Or anyone could teach me how to fix it by myself?
Thanks a lot.

**Comment by AngieHinrichs** [comment]
Perhaps you meant to send this to the IGV team at https://github.com/igvteam/igv ?  This is the mutalyzer repo.

**Comment by GiantVin** [comment]
Ooops!

thank you AngieHinriches
