### ISSUE TITLE
Name checker bug.

### ISSUE THREAD

**Issue by jfjlaros** [mutalyzer/mutalyzer#52]
This [variant](https://v3.mutalyzer.nl/namechecker/NG_016465.4:g.%5B112269dup;112274_112275insCCTCT%5D) inserts two consecutive `C`s. It is corrected however, to a duplication that does not contain two consecutive `C`s.

**Comment by mihailefter** [comment]
A wrong conversion to a duplication takes place. A simplified example with the same behavior is reference sequence `CTCTCTCTCTCTCTTG` with variants `[9dup;14_15insCCTCT]`.

![image](https://user-images.githubusercontent.com/21262869/146673204-ec5a656c-23b2-4720-9d47-3790242ff056.png)

The correct output in this case should be `10delinsCTCTCTC`.

For the original `NG_016465.4:g.[112269dup;112274_112275insCCTCT]` it should be `NG_016465.4:g.112270delinsCTCTCTC`.
