### ISSUE TITLE
Error When using local mutalyzer

### ISSUE THREAD

**Issue by HEKntg** [mutalyzer/mutalyzer#521]
My command line
`/usr/local/bin/mutalyzer NM_005228.4:c.2296_2297insTGGCCAGCG`
Then I got
`Message("Retriever", 4, "ERETR", "Could not retrieve NM_005228.4.")`
`1 Error, 0 Warnings.`

The network of this server is offline.
Mutalyzer script can't work offline?

**Comment by jfjlaros** [comment]
Mutalyzer retrieves its reference sequences from the NCBI, so unless these sequences are already present in the cache, retrieval will fail if the server is not online.
