### ISSUE TITLE
Alternate sequence extractor tool/feature?

### ISSUE THREAD

**Issue by esebesty** [mutalyzer/mutalyzer#524]
I was wondering if a tool exists or would be easy to implement for extracting the alternate sequence based on a variant description and the reference sequence. I'm looking for something that I can include in an R-based pipeline either using a web service, or some c++ code, but had no luck until now (would not want to use GATK, bcf-tools, etc). 

The Description extractor is _almost_ what I would need, and I guess the [extractor-core](https://github.com/mutalyzer/extractor-core) code could be used thru Rcpp or I could use the SOAP web-service.

However, instead of a service/function that returns `2C>G` for `ACGT` + `AGGT`, I'd like something that returns `AGGT` for `2C>G` + `ACGT`.

Any suggestions on where to look?

**Comment by jfjlaros** [comment]
Is [this](https://github.com/mutalyzer/mutator) what you are looking for?

**Comment by esebesty** [comment]
Thanks, the mutator library looks like a good start, although it doesn't seem to support all mutation types yet.

**Comment by jfjlaros** [comment]
Which types are you missing specifically?

**Comment by mihailefter** [comment]
@esebesty you can now also make use of the [mutator](https://github.com/mutalyzer/mutalyzer/blob/d979d7d3f3453231095d69b865a97aba932bb49b/mutalyzer/mutator.py#L10) from [Mutalyzer3](https://github.com/mutalyzer/mutalyzer), which is also available on [PYPI](https://pypi.org/project/mutalyzer/). Make sure that you [enable and populate the cache](https://mutalyzer.readthedocs.io/en/latest/usage.html) for faster processing times.
