### ISSUE TITLE
Is the cache still supported?

### ISSUE THREAD

**Issue by jpuntomarcos** [mutalyzer/mutalyzer#80]
Hi

I am following the exact instructions for enabling the cache:
https://mutalyzer.readthedocs.io/en/latest/usage.html

I execute all steps and example, but the client is always retrieving the data from the Mutalyzer server instead of using the cache. If I turn off my internet connection, I get the error `Reference NC_000022.11 could not be retrieved.`.  Am I missing anything?

Thanks a lot

**Comment by mihailefter** [comment]
@jpuntomarcos: Please check the latest documentation.
