### ISSUE TITLE
Problem with normalized position

### ISSUE THREAD

**Issue by mathieulemieux** [mutalyzer/mutalyzer#86]
While normalization of "NG_012337.3:g.**6**del" seems to work well:
https://v3.mutalyzer.nl/normalizer/NG_012337.3:g.6del

"NG_012337.3:g.**5**del" dosen't:
https://v3.mutalyzer.nl/normalizer/NG_012337.3:g.5del

Any clue why?
Does genomic coordinates works well on a gene sequence or it's only intended to be used with chromosome ones?

**Comment by jfjlaros** [comment]
Both descriptions are normalised to `NG_012337.3:g.6del`, which seems correct to me. The relevant part of the reference sequence is as follows,

    12345678
    GGGCTTGG...

so according to the [3' rule](https://varnomen.hgvs.org/recommendations/general/), the `T` at position 6 should be described as deleted.

Perhaps I misunderstand your question?
