### ISSUE TITLE
Could someone kindly provide an example of using Mutalyzer3 API with Python?

### ISSUE THREAD

**Issue by xiucz** [mutalyzer/mutalyzer#89]
Here is my code, can anyone correct it or give me one example?  Thank you very much!
```
import requests

transcript, c_num = "NM_000334.4", 92

headers = {
 'access-control-allow-origin': '*',
 'connection': 'keep-alive',
 'content-length': '290',
 'content-type': 'application/json',
 'date': 'Mon,25 Dec 2023 06:34:52 GMT',
 'server': 'nginx/1.18.0',
}   

data = {"reference_id": transcript,
         "from_coordinate_system": "c",
         "position": c_num,
         "to_coordinate_system": "g",
         "include_overlapping": "true",
       }
url = "https://mutalyzer.nl/api/position_convert"
requests.post(url, json = data)
```
```
ConnectionError: HTTPSConnectionPool(host='mutalyzer.nl', port=443): Max retries exceeded with url: /api/position_convert (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2afbbb9b5280>: Failed to establish a new connection: [Errno 110] Connection timed out'))

```
Best, 
xiucz

**Comment by jfjlaros** [comment]
The `position_convert` method can only be called using a GET request, please see the [documentation](https://mutalyzer.nl/api/) for more information.

Below is a working example.

```python
import requests


params = {
    'reference_id': 'NC_000011.10',
    'from_selector_id': 'NM_003002.4',
    'from_coordinate_system': 'c',
    'position': '92',
    'to_coordinate_system': 'g',
    'include_overlapping': 'false'}

url = 'https://mutalyzer.nl/api/position_convert'

response = requests.get(url, params=params)
print(response.text)
```

Output:

```json
{
  "input_model": {
    "reference": {
      "id": "NC_000011.10",
      "selector": {
        "id": "NM_003002.4"
      }
    },
    "coordinate_system": "c",
    "variants": [
      {
        "location": {
          "type": "point",
          "position": 92
        }
      }
    ]
  },
  "converted_model": {
    "reference": {
      "id": "NC_000011.10"
    },
    "coordinate_system": "g",
    "variants": [
      {
        "location": {
          "type": "point",
          "position": 112087896
        }
      }
    ]
  }
}
```

**Comment by jfjlaros** [comment]
I usually use the normalizer in combination with some not very well documented syntax that uses the build name as a reference ID, e.g., [GRCh38(NM_003002.4):c.92del](https://mutalyzer.nl/api/normalize/GRCh38(NM_003002.4)%3Ac.92del?only_variants=false).

Please note that both the position converter as well as the normalizer (using this syntax) convert between the `g.` and `c.` descriptions using the transcript information as annotated on the same reference reference. E.g., it converts between `NC_000011.10(NM_003002.4)` and `NC_000011.10`, not between `NM_003002.4` and `NC_000011.10`. The [mapper](https://mutalyzer.nl/mapper) can be used to convert between different reference sequences.

**Comment by jfjlaros** [comment]
> Mutalyzer2 would indeed be more user-friendly.

In what way? The examples above are using version 3.

> I just realized that this is the coordinate system of hg38(default).

The position converter does not use any genome build. `NC_000011.10` is part of the GRCh37 (hg19) genome build.

**Comment by jfjlaros** [comment]
You are welcome.
