### ISSUE TITLE
Coordinate system c does not match with M65131.1 c coordinate system.

### ISSUE THREAD

**Issue by ptaschner** [mutalyzer/mutalyzer#91]
Looking through old error reports, I decided to check the response of Mutalyzerv3's normalizer with M65131.1:c.361_371delinsGT. This resulted in the error Coordinate system c does not match with M65131.1 c coordinate system.
Mutalyzerv2 was able to check the description: https://v2.mutalyzer.nl/name-checker?description=M65131.1%3Ac.361_371delinsGT so I wonder what the problem with the c coordinate system is.

Thanks for your help.

**Comment by jfjlaros** [comment]
The only thing that caught my eye is that no exons are annotated in this reference file.

**Comment by mihailefter** [comment]
@ptaschner this is [fixed](https://mutalyzer.nl/normalizer/M65131.1:c.361_371delinsGT). Thanks for letting us know.
